language: go
go:
  - 1.12.x
install:
  - go get -u -v github.com/kardianos/govendor
  - go get -u -v github.com/gohugoio/hugo
  - (cd $GOPATH/src/github.com/gohugoio/hugo && govendor sync && go install)
deploy:
  provider: pages
  skip_cleanup: true
  GitHub_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

